# Generated by Django 4.0.2 on 2022-02-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_message_client_to_alter_message_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'in progress'), ('DELIVERED', 'delivered')], max_length=20),
        ),
    ]
