# Generated by Django 4.0.2 on 2022-02-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'progress'), ('DELIVERED', 'delivered')], default='progress', max_length=20),
        ),
    ]
