# Generated by Django 4.0.2 on 2022-03-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
